package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"app/internal/core/graph/model"
	"context"
	"fmt"
)

// CreateRecord is the resolver for the createRecord field.
func (r *mutationResolver) CreateRecord(ctx context.Context, input model.CreateRecordInput) (*model.Record, error) {
	panic(fmt.Errorf("not implemented: CreateRecord - createRecord"))
}

// GetRecords is the resolver for the getRecords field.
func (r *queryResolver) GetRecords(ctx context.Context, filter model.DefaultFilterInput) (*model.PaginatedRecordList, error) {
	panic(fmt.Errorf("not implemented: GetRecords - getRecords"))
}

// GetRecordByPostID is the resolver for the getRecordByPostId field.
func (r *queryResolver) GetRecordByPostID(ctx context.Context, filter model.GetByPostIDInput) (*model.Record, error) {
	panic(fmt.Errorf("not implemented: GetRecordByPostID - getRecordByPostId"))
}
