package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"app/internal/core/graph/model"
	"context"
	"fmt"
)

// CreateRoute is the resolver for the createRoute field.
func (r *mutationResolver) CreateRoute(ctx context.Context, input model.CreateRouteInput) (*model.Route, error) {
	panic(fmt.Errorf("not implemented: CreateRoute - createRoute"))
}

// DeleteRoute is the resolver for the deleteRoute field.
func (r *mutationResolver) DeleteRoute(ctx context.Context, id string) (*model.Route, error) {
	panic(fmt.Errorf("not implemented: DeleteRoute - deleteRoute"))
}

// GetRoutes is the resolver for the getRoutes field.
func (r *queryResolver) GetRoutes(ctx context.Context, filter model.DefaultFilterInput) (*model.PaginatedRouteList, error) {
	panic(fmt.Errorf("not implemented: GetRoutes - getRoutes"))
}

// GetRoute is the resolver for the getRoute field.
func (r *queryResolver) GetRoute(ctx context.Context, id string) (*model.Route, error) {
	panic(fmt.Errorf("not implemented: GetRoute - getRoute"))
}
